name: streamcore_chatui
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test: ^1.15.0
  test_process: ^2.0.0
  shelf_web_socket: ^1.0.1
  web_socket_channel: ^2.2.0
  dart_amqp: ^0.2.1