name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 5
    - uses: YassinEldeeb/has-changed-path@v2.1
      id: changed-package
      with:
        paths: ./ChatUI
    - uses: docker/login-action@v2.0.0
      if: steps.changed-package.outputs.changed == 'true'
      with: 
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - uses: docker/metadata-action@v4.0.1
      if: steps.changed-package.outputs.changed == 'true'
      id: meta
      with:
        images: ghcr.io/exlted/streamcore-chat-ui
        tags: |
          type=sha
          rype=raw,value=latest,enable={{is_default_branch}}
    - name: Build the Docker image
      if: steps.changed-package.outputs.changed == 'true'
      uses: docker/build-push-action@v2
      with:
        context: ./ChatUI
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
