name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2.0.0
      with: 
        registry: ghcr.io
        username: ${{github.repository_owner}}
        password: ${{secrets.REGISTRY_TOKEN}}
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./ChatUI
        push: true
        tags: |
          ghcr.io/streamcore-chat-ui:${{github.ref}}
          ghcr.io/streamcore-chat-ui:latest
