name: Entire Project CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-chat_objects:
    uses: ./.github/workflows/publish-crate.yml
    with:
      path: ./Shared_Code/Rust/chat_objects
    secrets:
      cargo: ${{ secrets.CARGO_TOKEN }}
  build-message_client:
    uses: ./.github/workflows/publish-crate.yml
    with:
      path: ./Shared_Code/Rust/message_client
    secrets:
      cargo: ${{ secrets.CARGO_TOKEN }}
  build-trovo:
    needs: [build-chat_objects, build-message_client]
    uses: ./.github/workflows/publish-docker-images.yml
    with:
      path: ./Trovo
      image_name: ghcr.io/exlted/streamcore-chat-trovo
    secrets:
      username: ${{ github.repository_owner }}
      password: ${{ secrets.REGISTRY_TOKEN }}

  build-twitch:
    needs: [build-chat_objects, build-message_client]
    uses: ./.github/workflows/publish-docker-images.yml
    with:
      path: ./Twitch
      image_name: ghcr.io/exlted/streamcore-chat-twitch
    secrets:
      username: ${{ github.repository_owner }}
      password: ${{ secrets.REGISTRY_TOKEN }}

  build-vstream:
    needs: [build-chat_objects, build-message_client]
    uses: ./.github/workflows/publish-docker-images.yml
    with:
      path: ./VStream
      image_name: ghcr.io/exlted/streamcore-chat-vstream
    secrets:
      username: ${{ github.repository_owner }}
      password: ${{ secrets.REGISTRY_TOKEN }}

  build-youtube:
    uses: ./.github/workflows/publish-docker-images.yml
    with:
      path: ./Youtube
      image_name: ghcr.io/exlted/streamcore-chat-youtube-ingest
    secrets:
      username: ${{ github.repository_owner }}
      password: ${{ secrets.REGISTRY_TOKEN }}

  build-youtube-rewrite:
    needs: [build-chat_objects, build-message_client]
    uses: ./.github/workflows/publish-docker-images.yml
    with:
      path: ./Youtube
      image_name: ghcr.io/exlted/streamcore-chat-youtube-ingest-rewrite-test
    secrets:
      username: ${{ github.repository_owner }}
      password: ${{ secrets.REGISTRY_TOKEN }}

  build-chatui:
    needs: [build-chat_objects, build-message_client]
    uses: ./.github/workflows/publish-docker-images.yml
    with:
      path: ./ChatUI
      image_name: ghcr.io/exlted/streamcore-chat-ui
    secrets:
      username: ${{ github.repository_owner }}
      password: ${{ secrets.REGISTRY_TOKEN }}
