name: Entire Project CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-chat_objects:
    runs-on: ubuntu-latest
    build-chat_objects-crate:
      uses: ./.gitub/workflows/publish-crate.yml
      with:
        path: ./SharedCode/Rust/chat_objects
      secrets:
        cargo: ${{ secrets.CARGO_TOKEN }}
  build-trovo:
    runs-on: ubuntu-latest
    needs: [build-chat_objects]
    build-trovo-image:
      uses: ./.github/workflows/publish-docker-images.yml
      with:
        path: ./Trovo
        image_name: ghcr.io/exlted/streamcore-chat-trovo

  build-twitch:
    runs-on: ubuntu-latest
    needs: [build-chat_objects]
    build-trovo-image:
      uses: ./.github/workflows/publish-docker-images.yml
      with:
        path: ./Twitch
        image_name: ghcr.io/exlted/streamcore-chat-twitch

  build-youtube:
    runs-on: ubuntu-latest
    build-trovo-image:
      uses: ./.github/workflows/publish-docker-images.yml
      with:
        path: ./Youtube
        image_name: ghcr.io/exlted/streamcore-chat-youtube-ingest

  build-chatui:
    runs-on: ubuntu-latest
    build-trovo-image:
      uses: ./.github/workflows/publish-docker-images.yml
      with:
        path: ./ChatUI
        image_name: ghcr.io/exlted/streamcore-chat-ui
