name: Publish Docker Image

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      image_name:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 5
    - uses: YassinEldeeb/has-changed-path@v2.1
      id: changed-package
      with:
        paths: ${{ inputs.path }}
    - uses: docker/login-action@v2.0.0
      if: steps.changed-package.outputs.changed == 'true'
      with: 
        registry: ghcr.io
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
    - uses: docker/metadata-action@v4.0.1
      if: steps.changed-package.outputs.changed == 'true'
      id: meta
      with:
        images: ${{ inputs.image_name }}
        tags: |
          type=sha
          rype=raw,value=latest,enable={{is_default_branch}}
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      if: steps.changed-package.outputs.changed == 'true'
      with:
        context: ${{ inputs.path }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}